### ISSUE TITLE
How do you run this on a Windows machine?

### ISSUE THREAD

**Issue by eonist** [Nican/Furland#1]
Asking for a friend.

Thanks

**Comment by timonsku** [comment]
Yea some build instruction would be great!
Can't get it built with VS2019

**Comment by Nican** [comment]
@eonist @timonsku I did not realize people were filing bug reports here. xD

I developed on Windows. What errors are you getting?

**Comment by eonist** [comment]
Maybe like @timonsku wrote. Make some basic instructions in a readme? Thanks. Looks great so far!

**Comment by Nican** [comment]
@eonist I left instructions on a `README.md`. Take a look, please.

**Comment by eonist** [comment]
@Nican Thanks 💚
